[package]
name = "mindus"
version = "1.3.4"
edition = "2021"
description = "A library for working with mindustry data formats (eg schematics and maps) (fork of plandustry)"
authors = [
  "KosmosPrime <5663514+KosmosPrime@users.noreply.github.com>",
  "bend-n <bend.n@outlook.com>",
]
repository = "https://github.com/bend-n/mindus.git"
license = "GPL-3.0"
exclude = [".github/", "items.py"]


[dependencies]
flate2 = { version = "1.0", features = ["zlib"], default-features = false }
base64 = "0.21.2"
paste = "1.0.12"
strconv = "0.1"
image = { version = "0.24.6", features = ["png"], default-features = false }
const-str = "0.5.5"
color-hex = "0.2.0"
zip = { version = "0.6.6", features = ["zstd"], default-features = false }
tinyrand = "0.5.0"
tinyrand-std = "0.5.0"
dashmap = "5.4.0"
fast_image_resize = "2.7.3"
thiserror = "1.0.41"
bobbin-bits = "0.1.1"
blurslice = "0.1.0"

[build-dependencies]
zip = { version = "0.6.6", features = ["zstd"], default-features = false }
walkdir = "2"

[[bin]]
name = "plandustry"
path = "src/exe/mod.rs"

[profile.release]
debug = 2
opt-level = 3
lto = true
incremental = true

[dev-dependencies]
diff = "0.1"
