[package]
name = "plandustry"
version = "1.0.1"
edition = "2021"
description = "A command-line tool for working with Mindustry schematics"
authors = ["KosmosPrime <5663514+KosmosPrime@users.noreply.github.com>"]
repository = "https://github.com/KosmosPrime/plandustry.git"
license = "GPL-3.0"

[dependencies]
flate2 = { version = "1.0", features = ["zlib"], default-features = false }
base64 = "0.21.2"
paste = "1.0.12"
strconv = { path = "strconv" }
image = { version = "0.24.6", features = ["png"], default-features = false }
const-str = "0.5.5"
color-hex = "0.2.0"

[[bin]]
name = "plandustry"
path = "src/exe/mod.rs"
