use crate::content::content_enum;

content_enum!
{
	pub enum Type / Unit for u16 | TryFromU16Error
	{
		Dagger => "dagger",
		Mace => "mace",
		Fortress => "fortress",
		Scepter => "scepter",
		Reign => "reign",
		Nova => "nova",
		Pulsar => "pulsar",
		Quasar => "quasar",
		Vela => "vela",
		Corvus => "corvus",
		Crawler => "crawler",
		Atrax => "atrax",
		Spiroct => "spiroct",
		Arkyid => "arkyid",
		Toxopid => "toxopid",
		Flare => "flare",
		Horizon => "horizon",
		Zenith => "zenith",
		Antumbra => "antumbra",
		Eclipse => "eclipse",
		Mono => "mono",
		Poly => "poly",
		Mega => "mega",
		Quad => "quad",
		Oct => "oct",
		Risso => "risso",
		Minke => "minke",
		Bryde => "bryde",
		Sei => "sei",
		Omura => "omura",
		Retusa => "retusa",
		Oxynoe => "oxynoe",
		Cyerce => "cyerce",
		Aegires => "aegires",
		Navanax => "navanax",
		Alpha => "alpha",
		Beta => "beta",
		Gamma => "gamma",
		Stell => "stell",
		Locus => "locus",
		Precept => "precept",
		Vanquish => "vanquish",
		Conquer => "conquer",
		Merui => "merui",
		Cleroi => "cleroi",
		Anthicus => "anthicus",
		AnthicusMissile => "anthicus-missile",
		Tecta => "tecta",
		Collaris => "collaris",
		Elude => "elude",
		Avert => "avert",
		Obviate => "obviate",
		Quell => "quell",
		QuellMissile => "quell-missile",
		Disrupt => "disrupt",
		DisruptMissile => "disrupt-missile",
		Renale => "renale",
		Latum => "latum",
		Evoke => "evoke",
		Incite => "incite",
		Emanate => "emanate",
		Block => "block",
		Manifold => "manifold",
		AssemblyDrone => "assembly-drone",
		ScatheMissile => "scathe-missile",
	}
}
